---
title: "ループ生成2"
author: "Nishida Norimitsu"
date: "2019/9/2"
output: powerpoint_presentation
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(tidyverse)
knitr::opts_chunk$set(echo = FALSE)
```


```{r}
#アルファベット毎に１から20のどれかの数字を設定
dat <- tibble(type = LETTERS) %>% 
  mutate(repeats = sample(1:20, 26, replace=TRUE))

```

前回の動画で、最後にでてきたNULLを消す方法を考えます  
NULLが表示されたのは、map関数が帰り値を出力する  
仕様になっているからです。  

* これを避けるには、forループを利用する
* mapと同じ動作をするが帰り値を返さないwalk関数を利用する

のどちらかになります。

どちらもやってみましょう！

## FORループでの出力

```{r, results="asis"}
for(i in 1:3){ #とりあえず3個だけ出力します
  foralpha <- dat$type[i]
  fornumber <- dat$repeats[i]
  
  cat(str_glue("## {foralpha}:FORループ"),"\n")
  cat(         "\n")
  cat(str_glue("* ランダムに生成された数字は:{fornumber}"),"\n")
  cat(         "\n")
}
```

## Walkを利用した出力

```{r, results="asis"}
walk(1:3, ~{ #こっちも3個
  alphabet  <- dat$type[.]
  number    <- dat$repeats[.]
  
  cat(str_glue("## {alphabet}"),"\n")
  cat(         "\n")
  cat(str_glue("* ランダムに生成された数字は:{number}"),"\n")
  cat(         "\n")
})
```

次は、グラフ描画と表の描画も同じ作戦でいけるかを検証します